apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
        - name: python-app
          image: my-python-app:ci
          env:
            - name: DB_HOST
              value: "mysql-service"
            - name: DB_NAME
              value: "mydb"
            - name: DB_USER
              value: "root"
            - name: DB_PASS
              value: "rootpassword"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: python-service
spec:
  type: NodePort
  selector:
    app: python-app
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080

